### PR TITLE
Upgrade builder to go 1.13

### LINKED ISSUE #238: Build error: cannot find module providing package crypto/ed25519
Building the image fails with "build caddy: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519".

### PR DESCRIPTION
**Pull request by TomFaulkner**
Fixes https://github.com/abiosoft/caddy-docker/issues/238

### CODE REVIEW

**Comment by ShiromMakkad** [comment]
I tried setting my docker build command to point to this repo instead of the regular one, but I still got the same error. Is it possible for you to fix this?

**Comment by TomFaulkner** [comment]
Sorry for the delay, I didn't see this before. Did you get it resolved, if not, do you have logs?

**Comment by ShiromMakkad** [comment]
The original repo got updated with the golang update

**Comment by TomFaulkner** [comment]
Glad to hear that.

**Pull request merged**
